# Surface Immunity {-}

**Led by Cyril Zipfel**

The first layer of plant innate immunity depends on the recognition of microbes via the perception of pathogen-associated molecular patterns (PAMPs) or damage-associated molecular patterns (DAMPs) by plasma membrane-localized pattern recognition receptors (PRRs). Plant PRRs are ligand-binding receptor kinases or receptor-like proteins that exist in multi-protein complexes to transduce intracellular immune signaling by triggering downstream phosphorylation cascades [@Couto:2016kq]. The Arabidopsis leucine-rich repeat receptor kinases (LRR-RKs) FLS2 and EFR are well-studied PRRs that bind the bacterial PAMPs flagellin and EF-Tu (or their immunogenic epitopes flg22 and elf18), respectively. In both cases, ligand-binding triggers rapid hetero-oligomerization with SERK co-receptors. Of these, BAK1/SERK3 and its closest paralog BKK1/SERK4 are the major regulators of FLS2- and EFR-dependent signaling. Intriguingly, BAK1 and other SERKs are also involved in various non-immune signaling pathways [@Ma:2016eu]. An allele of _BAK1_ specifically affected in PTI, _bak1-5_, enabled the uncoupling of BAK1’s functions in PTI, brassinosteroid (BR) signaling and cell death control [@Schwessinger:2011ku], allowing a detailed characterization of BAK1 in immune signaling without the influence of the morphological defects observed for other _BAK1_ alleles.

The plasma membrane-associated receptor-like cytoplasmic kinase (RLCK) BIK1 is an immediate convergent substrate of several different PRRs as well as BAK1 [@Couto:2016kq]. In response to PAMP perception, BIK1 is phosphorylated and released from the receptor complex and subsequently phosphorylates the NADPH oxidase RBOHD, which is required to produce reactive oxygen species (ROS), one of the first hallmark responses triggered after PAMP perception [@Kadota:2014bi; @Li:2014dx]. Another early PTI response is the influx of apoplastic Ca^2+^ via yet unknown channels, a response that is also BIK1-dependent [@Li:2014dx; @Ranf:2014fg; @Seybold:2014wt]. Subsequently, PAMP perception results in the activation of MAP kinase cascades and calcium-dependent protein kinases, which ultimately results in the transcriptional reprogramming of the cell mostly via WRKY transcription factors and ultimately to the restriction of pathogen growth [@Couto:2016kq]. Later responses associated with FLS2 and EFR activation include increased ethylene biosynthesis, callose deposition, and inhibition of seedling growth [@Boller:2009hu].

## Keynote Lecture {-}

### Stefanie Ranf - Specificity of LORE-dependent lipopolysaccharide immune sensing in Arabidopsis {-}
**Phytopathology, TUM School of Life Sciences, Technical University of Munich, Freising-Weihenstephan, Germany**

Innate immunity, triggered upom recognition of microbe-associated molecular patterns (MAMPs) by specific host receptors, is crucial for animals and plants. Cell surface components such as lipopolysaccharide (LPS), peptidoglycan and flagellin are typical MAMPs as they are vital for microbial survival and common to whole microbial classes. LPS, in particular the endotoxic lipid A moiety, of Gram-negative bacteria is sensed as MAMP in mammals through different extra- and intracellular LPS receptors. Recently, we found that the receptor-like kinase LORE (LipoOligosaccharide-specific Reduced Elicitation), which belongs to the plant-specific class of bulb-type lectin S-domain-1 kinases (SD1-RLKs), mediates sensitive perception of Pseudomonas LPS in Arabidopsis. The lipid A moiety from Pseudomonas LPS alone is sufficient to induce LORE-dependent immune responses.
Interestingly, LORE specifically senses Pseudomonas and Xanthomonas but not the typical enterobacterial LPS e.g. of Escherichia coli. In mammals, on the contrary, enterobacterial LPS is the most potent immune activator, whereas Pseudomonas LPS is only a weak agonist due to structural differences within the lipid A. Thus, both mammals and plants evolved to sense LPS via its lipid A moiety but, apparently, with distinct epitope specificities and through structurally unrelated receptors. 


### About Stefanie Ranf {-}

> Since March 2016 - Independent Emmy-Noether group leader at the Technical University of Munich, Chair of Phytopathology
>
> Jan. 2013 – Feb. 2016 - Junior group leader at the Technical University of Munich, Chair of Phytopathology, Prof. Dr. Ralph Hückelhoven
>
> May 2011 – Dec. 2012 - Postdoctoral research with Prof. Dr. Dierk Scheel and Dr. Justin Lee, Department of Stress and Developmental Biology, Institute of Plant Biochemistry (IPB), Halle (Saale)
>
> Jan. 2005 – Apr. 2011 - Ph.D. thesis with Prof. Dr. Dierk Scheel and Dr. Justin Lee, Department of Stress and Developmental Biology, Institute of Plant Biochemistry (IPB), Halle (Saale)
>
> Oct. 2003 – Dec. 2004 - Research fellow with Prof. Dr. Johannes Stratmann, University of South Carolina, USA
>
> Oct. 1998 – Feb. 2003 - Studies of Biochemistry at the Universität Regensburg 

\newpage

## Practical Session - Analysing Surface Immunity {-}

**Led by Martin Stegmann**

### Aims and Objectives {-}

1. Understanding of and hands on experience in classical methods to analyse PTI responses in the model organism _Arabidopsis thaliana_
2. Testing the importance of critical PTI regulators, mainly by analysing the impact of PRRs and PRR-associated RLKs on the activation of PTI signalling 
3. Understanding the contribution of PTI on plant immunity against adapted bacterial pathogens

The practical session “Surface Immunity” will consist of a pedagogical lecture on the biochemical and molecular biological techniques used to investigate the molecular basis of PTI signaling, and to identify novel PAMPs or PRRs. We will demonstrate some of the classical methods used to analyze downstream PTI responses, such as ROS production, MAPK activation, seedling growth inhibition and surface immunity upon spray infection with bacterial pathogens.

For measuring the PAMP-triggered ROS burst, we will make use of a luminescence-based assay, which enables the detection of apoplastic ROS that can be monitored live with a charge-coupled device camera. This is a fast and easy quantitative assay that can be used, in many cases, to study early PTI signalling in a given mutant compared to a wild type control.

In addition, we will assay for the induction of a MAPK cascade, specifically for the PAMP-induced phosphorylation of the four Arabidopsis MAPKs MPK3, MPK4, MPK6 and MPK11. Their activation can be detected within a few minutes after PAMP treatment by western blot analysis using a well-established commercial antibody that was raised to detect phosphorylated MAPKs in mammalian systems.
Prolonged exposure to PAMPs results in a growth arrest of seedlings, which can be used as a quantitative measure for the capability of a given genotype to respond to different stimuli. We will look at different Arabidopsis lines exposed to PAMPs for several days and assess the resulting growth differences compared to mock grown seedlings.

Finally, PAMP-triggered immunity contributes to the basal resistance of plants against adapted pathogens. In the frame of the practical session we will assess the differences in susceptibility of known PTI pathway mutants to demonstrate the importance of PTI for plant resistance.
