# Translations and Tipping the Balance {-}

**Led by Matt Moscou and Peter Van Esse**

*Exploiting Knowledge of Plant Pathogen Interactions for Durable Disease Resistance*

In this module we will go into detail about how key insights can be used to breed and engineer resistant crops and develop durable disease solutions. We will discuss how pathogen genomics and knowledge of effectors can lead to an informed deployment of R genes and how effector biology can be used to accelerate breeding programs. We will discuss examples where resistance has been transferred between plant species to introduce novel resistance specificities [@Kawashima:2016hx; @Lacombe:2010ga; @Tai:1999wa]. We will also discuss the strengths and weaknesses of classical breeding. 

In the first session, we will introduce the current status of agricultural systems and how our approach to plant breeding effects our ability to maintain disease resistance. Current approaches rely on identifying resistance in elite, landrace, and wild cultivars, identifying markers associated with resistance, and the use of marker-assisted selection to introduce resistance into elite accessions. While natural variation has been the primary source of resistance, pioneering work in nonhost species has paved the way forward for accessing a broader range of resistance genes for agriculture. We will discuss how recent technology including high-throughput sequencing, transformation, gene editing, and synthetic biology will improve our ability to engineer next-generation crops. 

A comprehensive disease management strategy requires a detailed understanding of the interaction between pathogens and their host or hosts. As pathogens are diverse, the above outlined strategies require fine-tuning and rethinking for each individual situation. Novel incursions are particularly dangerous as they can hit unexpectedly, spread rapidly, and can cause a great deal of damage long before we can even begin to understand the pathogen and determine an effective plan of action. Globalization and climate change are major drivers of new incursions as habitats of pathogens or their vectors shift. Global trade and travel enables rapid spread of microbes from one habitat to another. A rapid identification of a novel pathogen is the first step to mount an effective and informed response by scientist, breeders and farmers. After this long term solutions need to be designed and put in place that require in depth knowledge on plant-pathogen interactions. In the second session, as a creative exercise, we will work on a long-term solution to a current disease problem.

In the final part of this module we shall explore how personal development and career choices can deviate from the classic academic route.  We realize that to successfully meet the challenges faced by agriculture in the coming years, leaders on all levels and aspects of agriculture will be required. As scientist are highly educated creative thinkers they are ideal candidates to take up leadership roles in large corporations or become successful entrepreneurs in start-up companies. We believe it is crucial to have the abilities define a career path in which you can excel and therefore we would like to spend the last lecture of this summer school on this forward thinking topic. 
```

## Keynote Lecture {-}

### Beat Keller - Molecular analysis of wheat – fungal pathosystems and applications in resistance breeding {-}
**Department of Plant and Microbial Biology, University of Zürich, Switzerland**

Several hundred resistance genes against fungal diseases have been genetically described in the gene pool of wheat and a few of them have been cloned. The molecular analysis of their origin, diversity and function has resulted in insight on their evolution and also suggested better ways for their use in classical as well as molecular breeding. For example, the discovery of molecular suppressor activities of certain powdery mildew resistance genes has resulted in a better understanding of earlier observations in wheat breeding and allows to predict breeding outcomes. The current focus of our work is on two different aspects of disease resistance in wheat: first we study the molecular basis of durable disease resistance and we focus here on the _Lr34_ gene which was originally described as a QTL for durable, quantitative disease resistance against the fungal pathogen leaf rust. Second, we are analyzing at the molecular level the interaction of wheat and the fungal pathogen powdery mildew. This work also includes the identification of pathogen determinants that are involved in resistance. 
The new developments in wheat genomics including the availability of a high-quality reference genome sequence allow us to develop more efficient ways to isolate resistance genes. There is a rapidly increasing number of innovative new approaches to clone genes from the wheat genome which I will discuss briefly, and we can expect many more resistance genes being isolated in the near future. The consequences of these developments for a better use of genetic diversity in wheat resistance breeding will be discussed.
The molecular diversity that has been revealed by studies on agronomically important resistance genes can inspire a number of research directions to improve resistance breeding. For example, natural diversity provides important clues how to engineer immune receptors for broader recognition spectrum. Furthermore, modification of gene expression as well as combination of genes using transgenic approaches has revealed novel ways to improve disease resistance. Several of these approaches will be presented for the case of leaf rust and powdery mildew resistance in wheat.


### About Beat Keller {-}

> Dr. Keller received his PhD from the University of Basel, Switzerland, in 1985, and then was postdoctoral fellow at the Salk Institute for Biological Studies in La Jolla, San Diego with a long-term fellowship of the European Molecular Biology Organization. After returning to Europe he started a research group in collaboration with the wheat breeding program in Switzerland and became a full professor for Plant Molecular Biology at the University of Zurich in 1997.
The group of Dr. Keller has focused on the molecular understanding of fungal disease resistance in the wheat, maize and barley crop plants. This has resulted in the molecular identification of a number of agronomically important resistance genes. More recently, the group has started a large project on the wheat powdery mildew pathogen to understand resistance at the molecular level. In addition, fungal pathogenomics is used to study the evolution of this highly host-specific pathogen.
Dr. Keller was Vice-president of the Swiss Academy of Sciences from 2000-2006, has led several large research consortia in Switzerland and was an ERC Advanced Investigator grant holder from 2010 to 2015. He is a member of the Research Council of the Swiss National Science Foundation and currently Head of the Division of Biology at the University of Zurich.


## Practical Session - QTL Analysis  {-}

**Led by Matt Moscou**

### Aims and Objectives {-}

  1. Introduction to genetics through practice.
  2. Introduce basic R packages for QTL analysis, understand how to link genotype (genetic maps) with phenotype (continuous/discrete measurements) with R/qtl.

## Practical Session - Designing Durable Disease Solutions  {-}

**Led by Peter van Esse**

### Aims and Objectives {-}

  1. Familiarize ourselves with lateral thinking
  2. Brainstorm on potential solutions for a current disease problem in agriculture

#### Further Reading {-}

The impact of crop protection on agricultural production, @Popp:102401

Mendel's laws of inheritance and wheat breeding, @biffen_1905

Pathogen population genetics, evolutionary potential, and durable resistance, @McDonald:2002da
